-- Tabelas para API Movimentos Geral (api_omie_movimentos - Geral.py)
-- titulos_pagos: res_cLiquidado = 'S', det_cGrupo = 'CONTA_A_RECEBER'
-- titulos_a_vencer: res_cLiquidado = 'N', det_cGrupo = 'CONTA_A_RECEBER', det_dDtPrevisao > data de hoje (variável, sempre o dia da execução do ETL)
-- chave_empresa_cod_cliente = empresa & det_nCodCliente (armazenado no insert)
-- Qtde_dias_recebimento: calculado no Supabase = GREATEST(0, det_dDtPagamento - det_dDtPrevisao) em dias

-- 1) Títulos pagos
CREATE TABLE IF NOT EXISTS public.titulos_pagos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa text NOT NULL,
  "ValAberto_validado" numeric(20, 5),
  det_cCPFCNPJCliente text,
  categ_validada text,
  det_cNumDocFiscal text,
  det_dDtAlt date,
  det_dDtPrevisao date,
  det_dDtPagamento date,
  det_nCodTitulo bigint,
  chave_empresa_cod_cliente text NOT NULL,
  Qtde_dias_recebimento integer GENERATED ALWAYS AS (
    GREATEST(0, (det_dDtPagamento::date - det_dDtPrevisao::date))
  ) STORED,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_titulos_pagos_empresa ON public.titulos_pagos(empresa);
CREATE INDEX IF NOT EXISTS idx_titulos_pagos_chave ON public.titulos_pagos(chave_empresa_cod_cliente);
CREATE INDEX IF NOT EXISTS idx_titulos_pagos_dt_previsao ON public.titulos_pagos(det_dDtPrevisao);
CREATE INDEX IF NOT EXISTS idx_titulos_pagos_dt_pagamento ON public.titulos_pagos(det_dDtPagamento);

COMMENT ON TABLE public.titulos_pagos IS 'Títulos pagos (res_cLiquidado=S, det_cGrupo=CONTA_A_RECEBER) - API Movimentos Geral';
COMMENT ON COLUMN public.titulos_pagos.chave_empresa_cod_cliente IS 'empresa & det_nCodCliente';
COMMENT ON COLUMN public.titulos_pagos.Qtde_dias_recebimento IS 'GREATEST(0, det_dDtPagamento - det_dDtPrevisao) em dias inteiros';

-- 2) Títulos a vencer
CREATE TABLE IF NOT EXISTS public.titulos_a_vencer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa text NOT NULL,
  "ValAberto_validado" numeric(20, 5),
  det_cCPFCNPJCliente text,
  categ_validada text,
  det_cNumDocFiscal text,
  det_dDtAlt date,
  det_dDtPrevisao date,
  det_dDtPagamento date,
  det_nCodTitulo bigint,
  chave_empresa_cod_cliente text NOT NULL,
  Qtde_dias_recebimento integer GENERATED ALWAYS AS (
    CASE
      WHEN det_dDtPagamento IS NOT NULL AND det_dDtPrevisao IS NOT NULL
      THEN GREATEST(0, (det_dDtPagamento::date - det_dDtPrevisao::date))
      ELSE NULL
    END
  ) STORED,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_titulos_a_vencer_empresa ON public.titulos_a_vencer(empresa);
CREATE INDEX IF NOT EXISTS idx_titulos_a_vencer_chave ON public.titulos_a_vencer(chave_empresa_cod_cliente);
CREATE INDEX IF NOT EXISTS idx_titulos_a_vencer_dt_previsao ON public.titulos_a_vencer(det_dDtPrevisao);
CREATE INDEX IF NOT EXISTS idx_titulos_a_vencer_dt_pagamento ON public.titulos_a_vencer(det_dDtPagamento);

COMMENT ON TABLE public.titulos_a_vencer IS 'Títulos a vencer (res_cLiquidado=N, det_cGrupo=CONTA_A_RECEBER) - API Movimentos Geral';
COMMENT ON COLUMN public.titulos_a_vencer.chave_empresa_cod_cliente IS 'empresa & det_nCodCliente';
COMMENT ON COLUMN public.titulos_a_vencer.Qtde_dias_recebimento IS 'GREATEST(0, det_dDtPagamento - det_dDtPrevisao) em dias inteiros (null se det_dDtPagamento null)';
